version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            NODE_ENV: production
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
            interval: 30s
            timeout: 10s
            retries: 3
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
